@extends('layouts.main')
@section('content')
    <div class="header-image d-none d-md-block d-lg-block d-xl-block"></div>
    @include('layouts.frontend-navbar.navbar')
    <section>
        <div class="container py-5">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad commodi labore laboriosam laudantium nesciunt officiis perferendis perspiciatis recusandae tempora velit. Corporis culpa iste neque nobis optio recusandae sunt, unde voluptas.
        </div>
    </section>
@endsection
